### ISSUE TITLE
USAGE.md Inaccurate.

### ISSUE THREAD

**Issue by BubbaJuice** [ubipo/shrinkwrap#1]
Hey, on this GitHub [USAGE.md](https://github.com/ubipo/shrinkwrap/blob/master/USAGE.md) is wrong. It says to use balloon you use `Alt+Shift+W` when you actually use `Alt+Shift+B`. This could make using this plugin harder to find out for newcomers. Thanks, BubbaJuice

**Comment by ubipo** [comment]
Thanks!
