### ISSUE TITLE
When the balloon tool is used in an area it is not possible JOSM freezes

### ISSUE THREAD

**Issue by BubbaJuice** [ubipo/shrinkwrap#4]
When the balloon tool is used in an area it is not possible JOSM freezes. Adding a stop after a certain amount of time might solve this.

**Comment by ubipo** [comment]
Thanks! Added a 3 second timeout (and iteration limit)

**Comment by ubipo** [comment]
[Published as v1.0.6](https://github.com/ubipo/shrinkwrap/releases/tag/v1.0.6) and available in the plugin browser (update JOSM to 19017 or later)
