### ISSUE TITLE
shrinkwrap seems not to be active since last update plugins

### ISSUE THREAD

**Issue by Jakkajakka** [ubipo/shrinkwrap#6]
shrinkwrap seems not to be active since last update plugins 2024-03-31
Menu stay's grey.

**Comment by ubipo** [comment]
Hmm, I've tried installing when not running and installing at runtime but cannot seem to trigger this bug. What version of JOSM are you running? Could you maybe also run JOSM from a terminal and provide the output log?

**Comment by Jakkajakka** [comment]
![afbeelding](https://github.com/ubipo/shrinkwrap/assets/11509181/5d1e5090-c2a9-46d7-b7f4-1bf20daf12f4)
![afbeelding](https://github.com/ubipo/shrinkwrap/assets/11509181/e610dc97-b18a-4eea-a31a-5e69587b0974)

**Comment by Kovoschiz** [comment]
Same on newest ver 19067, Linux Mint 20.2 Java 17.0.9. Reinstalling (manually deleted) has no effect. No special messages in debug mode. The plugin loads fine, and the 2 other actions work. Only "shrinkwrap" is always grayed out.  Hotkey doesn't work either, with no response.

**Comment by ubipo** [comment]
Fixed in [v1.1.3](https://github.com/ubipo/shrinkwrap/releases/tag/v1.1.3), should be added to JOSM's plugin list in a day or so
