### ISSUE TITLE
Best way to handle balloon into merge

### ISSUE THREAD

**Issue by Venefilyn** [ubipo/shrinkwrap#7]
What would be the best way to balloon something and then merge it when you have to add temporary ways?

E.g. here I have to add a temporary way to enclose an area

![image](https://github.com/ubipo/shrinkwrap/assets/6598829/72917e22-9cfd-4a15-93ac-da5310141cb2)

then I balloon it
![image](https://github.com/ubipo/shrinkwrap/assets/6598829/ff897800-fd21-4c9c-9c93-b3238e5e2efc)

And after merging the ballooned way with the forest I still have the temporary item
![image](https://github.com/ubipo/shrinkwrap/assets/6598829/4440c7d6-2dd7-4e16-b7e2-7b1eca0f49cd)

**Comment by ubipo** [comment]
Hmm, instead of the balloon method, I'd probably:
- Select the big way
- Add the two nodes that made up the temporary way to the selection (from the example)
- Use 'More tools' > 'Split Object' (Alt-X for me)
- Delete the small closed way left behind
