### ISSUE TITLE
Best way to handle wrapping existing way

### ISSUE THREAD

**Issue by Venefilyn** [ubipo/shrinkwrap#8]
In this screenshot I would've expected I could "shrinkwrap" but it's grayed out
![image](https://github.com/ubipo/shrinkwrap/assets/6598829/2625a7ef-cc38-40e3-bcb0-185f56df9976)

I feel like ballooning the area and then merging with the forest is an unnecessary step 
![image](https://github.com/ubipo/shrinkwrap/assets/6598829/d2a62137-320d-4d81-8e81-c44d3a43c20e)

What would be the fastest way to do this? I tend to do it quite a lot as it is a lot faster than individually connecting nodes

**Comment by ubipo** [comment]
Shrinkwrap should have been available in this case. Fixed in [v1.1.3](https://github.com/ubipo/shrinkwrap/releases/tag/v1.1.3), duplicate of #6
